global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # A scrape configuration containing exactly one endpoint to scrape:
  # Here it's Prometheus itself.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape configuration for MM-Rules matchmaking backend
  - job_name: 'mm-rules'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s
    honor_labels: true
    scheme: 'http'

  # Optional: Scrape Redis metrics if you have redis_exporter
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['host.docker.internal:6379']
  #   metrics_path: '/metrics'
  #   scrape_interval: 10s 